global:
  smtp_smarthost: 'smtp.example.com:587'  # Substitua pelo seu servidor SMTP
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'username'
  smtp_auth_password: 'password'

route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'your-email@example.com'  # Substitua pelo seu e-mail